version: "3.7"

services:

  mcp_evolution:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcp_evolution:latest
    env_file:
      - .env
    networks:
      - AcerolaNet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.mcp_evolution.rule=Host(`mcp-evolution.acerola.cloud`)
        - traefik.http.routers.mcp_evolution.entrypoints=websecure
        - traefik.http.routers.mcp_evolution.tls.certresolver=letsencryptresolver
        - traefik.http.services.mcp_evolution.loadbalancer.server.port=3001
        - traefik.http.services.mcp_evolution.loadbalancer.passHostHeader=true

networks:
  AcerolaNet:
    external: true
    name: AcerolaNet
